### ISSUE TITLE
Language server seems to be broken

### ISSUE THREAD

**Issue by imtbl** [mserajnik/dnh#1]
__If you are still on version `1.3.0` and everything seems to work, do not upgrade for now.__

After the [latest release](https://github.com/mserajnik/dnh/tree/1.4.0), the language server doesn't seem to work correctly, making any completion features that require it (everything aside from snippets) unavailable.

There are no obvious error messages and the language server _did_ work fine when testing the changes before publishing the new release, even after the dependency updates.

After that, it seemed to stop working completely, regardless if it's running in debug (for testing) or production mode.

Reverting to a previous version didn't have any effect either. This seems to indicate that it's an issue related to VS Code (maybe an incompatibility in a newer version?) rather than a new problem that didn't exist before the latest release.

~~Of course, there's also the possibility that it's a local issue. I will test on other machines and if it doesn't work there, I'll start debugging this when I find the time.~~ __Edit:__ I can confirm that it's not working on one of my other machines either, which means I'll have to dig deeper.

**Comment by a1e7de48f89e** [comment]
Figured out the problem: https://github.com/Microsoft/vscode-extension-samples/issues/156

Will be fixed in the upcoming `1.5.0` release.

**Comment by a1e7de48f89e** [comment]
Reopened because the issue (or one with the same symptoms) still persists when running the installed version from the marketplace. Everything works fine in debug though. Continuing to investigate.
